FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copy project files for restoring
COPY ["src/ApiGateway/MangaERP.ApiGateway/MangaERP.ApiGateway.csproj", "ApiGateway/MangaERP.ApiGateway/"]

RUN dotnet restore "ApiGateway/MangaERP.ApiGateway/MangaERP.ApiGateway.csproj"

# Copy the remaining source files and build
COPY src/ApiGateway /src/ApiGateway
WORKDIR "/src/ApiGateway/MangaERP.ApiGateway"
RUN dotnet publish "MangaERP.ApiGateway.csproj" -c Release -o /app/publish /p:UseAppHost=false -m:1 /p:UseSharedCompilation=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MangaERP.ApiGateway.dll"]
