using MediatR;
using MangaERP.BuildingBlocks.Infrastructure.Messaging;
using MangaERP.BuildingBlocks.Contracts.IntegrationEvents;
using MangaERP.Submission.Application.Ports;

namespace MangaERP.Submission.Application.Commands.ApproveSubmission;

public record ApproveSubmissionCommand(Guid SubmissionId, Guid ReviewerBoardUserId) : IRequest;

public class ApproveSubmissionHandler : IRequestHandler<ApproveSubmissionCommand>
{
    private readonly ISubmissionRepository _repository;
    private readonly IEventBus _eventBus;

    public ApproveSubmissionHandler(ISubmissionRepository repository, IEventBus eventBus)
    {
        _repository = repository;
        _eventBus = eventBus;
    }

    public async Task Handle(ApproveSubmissionCommand request, CancellationToken cancellationToken)
    {
        var submission = await _repository.GetByIdAsync(request.SubmissionId, cancellationToken)
            ?? throw new KeyNotFoundException($"Submission {request.SubmissionId} not found.");

        submission.Approve(request.ReviewerBoardUserId);
        await _repository.UpdateAsync(submission, cancellationToken);

        // Publish SubmissionApprovedEvent — consumed by Series service
        var integrationEvent = new SubmissionApprovedEvent(
            Guid.NewGuid(), DateTime.UtcNow,
            submission.Id, Guid.NewGuid(), // SeriesId generated by Series service
            submission.SubmitterId,
            submission.Title,
            submission.Genre,
            null);

        await _eventBus.PublishAsync(integrationEvent, cancellationToken);
    }
}
