using MangaERP.Shared.Domain.Abstractions;
using MangaERP.Identity.Domain.Enums;

namespace MangaERP.Identity.Domain.Entities;

/// <summary>
/// User entity. Corporate username is auto-generated by provisioning workflow.
/// PersonalEmail is the invitee's contact email (for invitation delivery).
/// AccountStatus tracks lifecycle: PendingActivation → Active.
/// </summary>
public class User : ISoftDeletable
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Username { get; set; } = string.Empty;         // corporate email e.g. anhnv.mgk@company.com
    public string Email { get; set; } = string.Empty;            // same as Username for login
    public string? PersonalEmail { get; set; }                   // invitee personal contact email
    public string PasswordHash { get; set; } = string.Empty;     // empty until activation
    public UserRole Role { get; set; } = UserRole.Reader;
    public AccountStatus AccountStatus { get; set; } = AccountStatus.Active;
    public string? FullName { get; set; }
    public string? AvatarUrl { get; set; }

    // Soft Delete
    public bool IsDeleted { get; set; } = false;
    public DateTime? DeletedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();
}

/// <summary>JWT refresh token — one-time use, revocable.</summary>
public class RefreshToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid UserId { get; set; }
    public string Token { get; set; } = string.Empty;
    public DateTime ExpiresAt { get; set; }
    public bool IsRevoked { get; set; } = false;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? RevokedAt { get; set; }
    public virtual User User { get; set; } = null!;
}

/// <summary>
/// JWT-based invitation token for the account provisioning flow.
/// Created when Admin provisions an account; consumed when user activates.
/// </summary>
public class InvitationToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Token { get; set; } = string.Empty;  // signed JWT string
    public Guid UserId { get; set; }
    public string PersonalEmail { get; set; } = string.Empty;
    public bool IsUsed { get; set; } = false;
    public DateTime ExpiresAt { get; set; }
    public DateTime? UsedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public virtual User User { get; set; } = null!;
}
