using MangaERP.Shared.Domain.Abstractions;
using MangaERP.Identity.Domain.Enums;

namespace MangaERP.Identity.Domain.Entities;

/// <summary>
/// User entity. Corporate username is auto-generated by provisioning workflow.
/// PersonalEmail is the invitee's contact email (for invitation delivery).
/// AccountStatus tracks lifecycle: PendingActivation → Active.
/// Role field is KEPT for backwards-compat with JWT generation.
/// The canonical role source is the UserRoles join table (RBAC).
/// </summary>
public class User : ISoftDeletable
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Username { get; set; } = string.Empty;         // corporate email e.g. anhnv.mgk@company.com
    public string Email { get; set; } = string.Empty;            // same as Username for login
    public string? PersonalEmail { get; set; }                   // invitee personal contact email
    public string PasswordHash { get; set; } = string.Empty;     // empty until activation
    public UserRole Role { get; set; } = UserRole.Reader;        // kept for JWT compat; RBAC via UserRoles
    public AccountStatus AccountStatus { get; set; } = AccountStatus.Active;
    public string? FullName { get; set; }
    public string? AvatarUrl { get; set; }
    public string? PhoneNumber { get; set; }
    public string? PenName { get; set; }
    public string? DrawingSoftwares { get; set; }
    public string? BankAccountNumber { get; set; }
    public Guid? ManagingTantouId { get; set; }
    public int DeadlineWarningCount { get; set; } = 0;

    // Navigation
    public virtual User? ManagingTantou { get; set; }

    // Soft Delete
    public bool IsDeleted { get; set; } = false;
    public DateTime? DeletedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    // RBAC: Many-to-Many with Roles via UserRoles join table
    public virtual ICollection<UserRole_Entity> UserRoles { get; set; } = new List<UserRole_Entity>();
}

/// <summary>JWT refresh token — one-time use, revocable.</summary>
public class RefreshToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid UserId { get; set; }
    public string Token { get; set; } = string.Empty;
    public DateTime ExpiresAt { get; set; }
    public bool IsRevoked { get; set; } = false;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? RevokedAt { get; set; }
    public virtual User User { get; set; } = null!;
}

/// <summary>
/// JWT-based invitation token for the account provisioning flow.
/// Created when Admin provisions an account; consumed when user activates.
/// </summary>
public class InvitationToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Token { get; set; } = string.Empty;  // signed JWT string
    public Guid UserId { get; set; }
    public string PersonalEmail { get; set; } = string.Empty;
    public bool IsUsed { get; set; } = false;
    public DateTime ExpiresAt { get; set; }
    public DateTime? UsedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public virtual User User { get; set; } = null!;
}

/// <summary>
/// RBAC Role entity — represents a named role in the system.
/// Seeded at startup with: MANGAKA, EDITORIAL_BOARD, EDITOR_IN_CHIEF, TANTOU_EDITOR, ADMIN.
/// </summary>
public class Role_Entity
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Name { get; set; } = string.Empty;   // e.g. "EDITORIAL_BOARD"
    public string? Description { get; set; }

    // Navigation
    public virtual ICollection<UserRole_Entity> UserRoles { get; set; } = new List<UserRole_Entity>();
}

/// <summary>
/// RBAC join table — User has many Roles, Role has many Users.
/// </summary>
public class UserRole_Entity
{
    public Guid UserId { get; set; }
    public Guid RoleId { get; set; }
    public DateTime AssignedAt { get; set; } = DateTime.UtcNow;

    public virtual User User { get; set; } = null!;
    public virtual Role_Entity Role { get; set; } = null!;
}
